projects:
  bibipapp-staging:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: 26e26qib7jfczeldjymwyvltnu
        maxDepth: 10
extensions:
  amplify:
    version: 3
